apiVersion: namespaceclass.akuity.io/v1
kind: NamespaceClass
metadata:
  name: internal-network
spec:
  resources:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-vpn-access-only
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      - Egress
      ingress:
      - from:
        - ipBlock:
            cidr: 10.0.0.0/8  # Example VPN CIDR
      egress:
      - to:
        - ipBlock:
            cidr: 10.0.0.0/8  # Example VPN CIDR
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: default-limits
    spec:
      limits:
      - default:
          memory: 512Mi
          cpu: 500m
        defaultRequest:
          memory: 256Mi
          cpu: 250m
        type: Container