apiVersion: namespaceclass.akuity.io/v1
kind: NamespaceClass
metadata:
  name: public-network
spec:
  resources:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-public-ingress
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      ingress:
      - from:
        - ipBlock:
            cidr: 0.0.0.0/0