apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceclasses.namespaceclass.akuity.io
spec:
  group: namespaceclass.akuity.io  # Match your API group in namespaceclass_types.go
  names:
    kind: NamespaceClass
    listKind: NamespaceClassList
    plural: namespaceclasses
    singular: namespaceclass
    shortNames:
      - nsc
  scope: Cluster  # NamespaceClass is cluster-scoped
  versions:
    - name: v1  # Match your API version in namespaceclass_types.go
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                resources:
                  type: array
                  description: "List of Kubernetes resources to be created in namespaces of this class"
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    description: "Raw Kubernetes resource definition"
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                lastUpdateTime:
                  type: string
                  format: date-time
                  description: "Last time the NamespaceClass was updated"
                managedNamespaces:
                  type: array
                  items:
                    type: string
                  description: "List of namespaces using this class"
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Namespaces
          type: integer
          jsonPath: .status.managedNamespaces
          description: Number of namespaces using this class
      subresources:
        status: {}  # Enable status subresource